name: CI/CD

on:
  push:
    branches:
      - main
      - develop
      - feature
  pull_request:
    branches:
      - main
      - develop
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Set chrome-sandbox permissions
      run: sudo chown root:root node_modules/electron/dist/chrome-sandbox && sudo chmod 4755 node_modules/electron/dist/chrome-sandbox

    - name: Install xvfb
      run: sudo apt-get install -y xvfb

    - name: Build the project
      run: npm run build

    - name: Run tests
      run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" npm start